### ISSUE TITLE
Tutorial: Using Backbone and Nooku

### ISSUE THREAD

**Issue by magneticmg** [nooku/guides.nooku.org#18]
Connected to nooku/www.nooku.org#7 . Breaking out into 
https://docs.google.com/a/timble.net/document/d/1Rq_fu2qAQ7-R9i9bC84KegYAXuDGO5uzDqVZNI_MeB4/edit#

**Comment by magneticmg** [comment]
@johanjanssens 

I'll give you an opportunity to comment on this piece before I do my last review/edit and turn it into an markdown file. 

Regarding the code in https://github.com/magneticmg/joomla-todo/tree/feature/7-backbone, how do you think we should deal with that? I'm not sure that including it in the master joomla-todo branch is the right move. Maybe a "./tutorials" branch set (like ./feature)? 
Note, the router.php file has one small change so that it works even when there is no menu item id, which could maybe go into the master. 

Thanks

**Comment by magneticmg** [comment]
Updated "Items" to "Tasks" in the tutorial and merged changes to the fork.

**Comment by johanjanssens** [comment]
@magneticmg Thanks will review. The router change I would put in master, the backbone code, good question, either in master or we separate tutorial branches as suggested. To reduce complexity of master  I like the idea of a tutorial branch.

**Comment by magneticmg** [comment]
@johanjanssens 

Latest revision completed. Some highlights:
* slightly more conversational and accessible in places. 
* I've decided the simplest way to keep the tutorial on message and get the user set up is to include the initial backbone assets in a "starting" branch of the Joomla Todo package. This eliminates any need to explain : how to get those assets, bower, composer, or any other tech and keeps things focused. 
* we have committed more to the 'follow along' approach 

I think we have a solid piece here. After you do your review I'll update the screenshots and get this into markdown.

**Comment by johanjanssens** [comment]
@magneticmg Excellent work, very happy with with the result, very solid. I have made some smaller changes, think this is ready to be moved in markdown.

**Comment by magneticmg** [comment]
Ok, screenshots are done and this is in markdown. 

@johanjanssens Note: I used Rastin's LICEcap to grab do a gif of the last POST a task part. Let me know what you think...I'd like it to be a little faster.

You can see it here: https://github.com/nooku/guides.nooku.org/commit/d9fd0b7dd4a4647329248cbfe569637c8b800df2#diff-6255330c5c361dc0b07d3f2b94eee7d5

**Comment by johanjanssens** [comment]
@magneticmg Nice work. Another tool you can consider is : http://recordit.co/  One thing when using Gif's is that it only plays when page is loaded. There are Gif players out there that wrap the give and provide a play button to replay it. Recordit provides this. Here is an example : http://recordit.co/BXKeIIWDaa

**Comment by magneticmg** [comment]
@johanjanssens 

This is up in the staging area (Thanks for that @stevenrombauts ) in http://staging.guides.nooku.org/tutorials/backbonejs-nooku-together.html 

Highlights: 
* each step corresponds to a commit
* each major section/step has a **composer command** to optionally run at the end

I think it is ready. I'll push it out tomorrow morning if there are no objections (we can always tweak it).
