### ISSUE TITLE
Parameterizable

### ISSUE THREAD

**Issue by magneticmg** [nooku/guides.nooku.org#25]
This has been part of #13 and https://timble.assembla.com/spaces/joomlatools-documentation/tickets/cardwall#/ticket:14 but should have its own ticket. 

https://docs.google.com/document/d/1UMpQYXzb3Uu7ISghaIl8S9Mcq0f19ihqp6-SYZDbL1M/edit

**Comment by magneticmg** [comment]
@johanjanssens I have cleaned up the language a fair bit and moved some things around. 
I think EAV related stuff could go into a blog post.

**Comment by johanjanssens** [comment]
@magneticmg Did another round of reviews. Getting there.

**Comment by tomjanssens** [comment]
Parameterizable has been released on [developer.joomlatools.com](http://developer.joomlatools.com/framework/models/database/behaviors/parameterizable.html).
