### ISSUE TITLE
Getting strted example dont'show description field

### ISSUE THREAD

**Issue by frankar** [nooku/guides.nooku.org#26]
in http://guides.nooku.org/get-started/your-first-todo-list-view.html

<?=$item->text?> must be <?=$item->description?>

**Comment by johanjanssens** [comment]
Thanks @frankar. We have moved our getting started guide to http://developer.joomlatools.com/framework/getting-started.html the typo has been fixed there. The Nooku guides will be redirected once all content has been moved.
